version: '3.8'

services:
  app:
    image: '231b128bbeef'
    container_name: secure
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/SpringSecure
    depends_on:
      - db_pg_15

  db_pg_15:
    image: postgres:15-alpine
    container_name: db
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: SpringSecure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres