spring:
  datasource:
    url: ${DB_URL}
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml
jpa:
  hibernate:
    ddl-auto: none
  open-in-view: false
