spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecure
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db/changelog/db-changelog.xml

  docker:
    compose:
      enabled: true
      file:


jpa:
  hibernate:
    ddl-auto: none

  open-in-view: false

