--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.person (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        email varchar(100) NOT NULL,
        password varchar(100) NOT NULL,
        is_account_non_expired boolean NOT NULL,
        is_account_non_locked boolean NOT NULL,
        s_credentials_non_expired boolean NOT NULL,
        is_enabled boolean NOT NULL
);

CREATE TABLE public.event (
        id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title varchar(30) NOT NULL,
        create_at date NOT NULL,
        description text
);